name: MLOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - run: pip install -r requirements.txt

    - name: Create folders
      run: |
        mkdir -p models
        mkdir -p metrics

    - run: |
        python src/train.py --run_name ci_run \
        --model rf \
        --n_estimators 100 \
        --feature_set all \
        --dataset_version v2